---
title: "README for torpor paper"
output: html_document
---

For paper titled:
"Torpid hummingbirds- energy savings in temperate and tropical sites"

Paper authors: Anusha Shankar\*, Rebecca J Schroeder\*, Susan M Wethington, Catherine H Graham, Donald R Powers

\*Equal authors

Code by: Anusha Shankar, github/nushiamme

Contact: anusha.shankar\@stonybrook.edu for questions about code

The code is organized by data type into 3 scripts, for 1. respirometry plots, 2. temperature plots, and 3. phylogenetic correcns and MCMCglmm models. Figures not listed here were conceptual figures made in powerpoint.

* **Torpor_respirometry_plots.R** - Needs input file *"Torpor_individual_summaries.csv"*; contains code for 
    + Figure 3: VO2 for broad-billed hummingbirds showing inflection point at 14-15 degC
    + Supplementary Figure S5: Duration of torpor per individual per night, as a function of the hour of entry
    + Supplementary Figure S6: Average hourly torpid energy savings relative to normothermy
    + Supplementary Figure S7: Average mass-corrected energy expenditure as a function of minimum hourly chamber temperature
    + Supplementary Figure S9: Total nighttime energy expenditure including rewarming (small black dots), and excluding rewarming (coloured dots), as a function of individual mass

* **Torpor_temperature_plots.R** - Needs input files *"Tc_AllSites_summ.csv"* and *"Ta_AllSites_summ.csv"*; Contains code for
    + Figure 2: Chamber Temp plots by hour, per site
    + Supplementary Figure S3: Ambient temp plots by hour, per site
    
* **Torpor_phylo_MCMCglmm_models.R** - Needs input files *"Torpor_individual_summaries.csv"* and ".tre" hummingbird phylogeny file from McGuire et al. 2014 (). Contains code for all the MCMCglmm models, analyses for the following tables, and plots
    + Supplementary Table S2: Stepwise model DIC values for parameter combinations in the nighttime energy expenditure MCMCglmm models
    + Supplementary Table S3: Comparing MCMCglmm stepwise model results for the rewarming models
    + Supplementary Figure S4: MCMCglmm model for the probability of entry into torpor as a function of individual capture mass
    + Supplementary Figure S8: MCMCglmm model for the nighttime energy expenditure as a function of torpor duration and minimum chamber temperature
    + Supplementary Figure S10: MCMCglmm model for rewarming energy expenditure (kJ) as a function of mass and chamber temperature
    